[package]
name = "fetch-wiki-examples"
version = "0.1.0"
authors = ["Jon Gjengset <jon@thesquareplanet.com>"]

[dependencies]
reqwest = "0.8.5"
scraper = "0.6.0"
regex = "1.0"
rusqlite = "0.13"
cli-agenda = "0.1.1"
